# Use an official Miniconda3 as a parent image
FROM continuumio/miniconda3

RUN conda create -n tss_env -y python=3.8 && \
    conda install -y -n tss_env -c conda-forge matplotlib multiprocess && \
    conda install -y -n tss_env -c bioconda pysam && \
    conda install -y -n tss_env -c anaconda numpy && \
    echo "source activate tss_env" > ~/.bashrc

# Set default command to start /bin/bash
ENV PATH /usr/local/bin:/opt/conda/envs/tss_env/bin:$PATH
ENV CONDA_DEFAULT_ENV tss_env

# 1. docker build -t eilalan/tss_env -f Dockerfile_tss .
# 2. docker run -it eilalan/tss_env
# 3. docker push eilalan/tss_env
