version: 1.2
workflows:
   - name: "IGVF-single_cell_pipeline"
     subclass: WDL
     primaryDescriptorPath: /multiome_pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - sw-synapse
         tags:
             - /.*/

    - name: "IGVF-sample-fastqs"
      subclass: WDL
      primaryDescriptorPath: /workflows/subwf-sample-fastqs.wdl
      filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - sw-synapse
         tags:
             - /.*/

