version: 1.2
workflows:
   - name: "IGVF-single_cell_pipeline"
     subclass: WDL
     primaryDescriptorPath: /multiome_pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - sw-synapse
         tags:
             - /.*/
