version: 1.2
workflows:
   - name: "IGVF-single_cell_pipeline"
     subclass: WDL
     primaryDescriptorPath: /multiome_pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - sw-kb-index
             - updated-qcs
         tags:
             - /.*/

   - name: "IGVF-sample_fastqs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_sample_fastqs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - sw-synapse
         tags:
             - /.*/

   - name: "IGVF-check_inputs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_check_inputs_synapse.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - updated-qcs
         tags:
             - /.*/
             
   - name: "IGVF-kb_index"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_kb_index.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - sw-kb-index
         tags:
             - /.*/