version: 1.2
workflows:
   - name: "IGVF-single_cell_pipeline"
     subclass: WDL
     primaryDescriptorPath: /multiome_pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - sw-synapse
             - updated-qcs
         tags:
             - /.*/

   - name: "IGVF-sample_fastqs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf_sample_fastqs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - sw-synapse
         tags:
             - /.*/

