# Use a base image with Python
FROM continuumio/miniconda3

# Install wget, tar, and other basic utilities
RUN apt-get update && apt-get install -y wget tar make g++ autoconf cmake git build-essential

# Install seqspec
RUN pip install seqspec

# dev environment
#RUN pip install --quiet git+https://github.com/IGVF/seqspec.git

# # # FOR DEBUG on local machine
# # # Create a directory for Jupyter notebooks
# RUN mkdir /notebooks

# # Copy spec.yaml, copy the notebook
# COPY spec.yaml /notebooks
# COPY preprocess.ipynb /notebooks

# # Install Jupyter Notebook
# RUN pip install jupyter

# # Set the working directory to /notebooks
# WORKDIR /notebooks

# # Expose port 8888 for Jupyter Notebook
# EXPOSE 8888

# # Start Jupyter Notebook on container startup
# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]


# docker build -t eilalan/seqspec_env:latest -f Dockerfile_seqspec .
# docker run -it eilalan/seqspec_env:latest bash
# docker push eilalan/seqspec_env:latest