FROM continuumio/miniconda3

RUN conda create -n seqspec_env -y python=3.8 && \
    conda run -n seqspec_env pip install seqspec && \
    echo "source activate seqspec_env" > ~/.bashrc
    

# Set default command to start /bin/bash
ENV PATH /usr/local/bin:/opt/conda/envs/seqspec_env/bin:$PATH
ENV CONDA_DEFAULT_ENV seqspec_env


# docker build -t eilalan/seqspec_env:latest -f Dockerfile_seqspec .
# docker run -it eilalan/seqspec_env:latest
# docker push eilalan/seqspec_env:latest

