FROM continuumio/miniconda3

RUN conda create -n cellatlas_env -y python=3.8 && \
    conda install -y -n cellatlas_env -c anaconda wget git && \
    conda install -y -n cellatlas_env -c conda-forge tar tree jq && \
    conda install -y -n cellatlas_env -c bioconda gget && \
    echo "source activate cellatlas_env" > ~/.bashrc

# Set default command to start /bin/bash
ENV PATH /usr/local/bin:/opt/conda/envs/cellatlas_env/bin:$PATH
ENV CONDA_DEFAULT_ENV cellatlas_env


# docker build -t eilalan/cellatlas_env:latest -f Dockerfile_cellatlas .
# docker run -it eilalan/cellatlas_env:latest bash
# docker push eilalan/cellatlas_env:latest
