# Use a base image with Python
FROM python:3.9-slim-buster

# Install wget, tar, and other basic utilities
RUN apt-get update && apt-get install -y wget tar make g++ autoconf cmake git build-essential

# Install tree
RUN wget --quiet ftp://mama.indstate.edu/linux/tree/tree-2.1.0.tgz \
    && tar -xf tree-2.1.0.tgz \
    && cd tree-2.1.0 \
    && make -j16 \
    && make install

# Install jq
RUN wget --quiet https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 \
    && chmod +x jq-linux64 \
    && mv jq-linux64 /usr/local/bin/jq

# Install cellatlas
RUN git clone https://github.com/cellatlas/cellatlas.git \
    && cd cellatlas \
    && pip install .

# Install seqspec
RUN pip uninstall -y seqspec
RUN pip install --quiet git+https://github.com/IGVF/seqspec.git

# Install gget
RUN pip install gget

# Install kb-python
RUN pip install kb-python

# Install bzip2 package
RUN apt-get install -y bzip2

# Install minimap
RUN wget --quiet https://github.com/lh3/minimap2/releases/download/v2.24/minimap2-2.24_x64-linux.tar.bz2 \
    && tar -jxf minimap2-2.24_x64-linux.tar.bz2 \
    && cp minimap2-2.24_x64-linux/minimap2 /usr/local/bin

# Install curses development package
RUN apt-get install -y libncurses5-dev

# Install zlib development package
RUN apt-get install -y zlib1g-dev

# Install libbzip2 development package
RUN apt-get install -y libbz2-dev

# Install liblzma development package
RUN apt-get install -y liblzma-dev

# Install samtools (with curses support)
RUN wget --quiet https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 \
    && tar -jxf samtools-1.17.tar.bz2 \
    && cd samtools-1.17/ \
    && ./configure --prefix=$(pwd) \
    && make \
    && make install

# Copy the samtools binary to a system-wide location
RUN cp samtools-1.17/samtools /usr/local/bin


# Install Genrich
RUN git clone https://github.com/jsh58/Genrich.git \
    && cd Genrich \
    && make \
    && cp Genrich /usr/local/bin


# Install bedtools
RUN wget --quiet https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools.static.binary \
    && chmod +x bedtools.static.binary \
    && mv bedtools.static.binary /usr/local/bin/bedtools


# Install kallisto and bustools
RUN git clone https://github.com/pachterlab/kallisto \
    && cd kallisto \
    && git checkout shareseq \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && cp src/kallisto /usr/local/bin \
    && cp src/kallisto $(pip show kb-python | grep "Location" | cut -f2 -d":")/kb_python/bins/linux/kallisto/kallisto \
    && cp $(pip show kb-python | grep "Location" | cut -f2 -d":")/kb_python/bins/linux/bustools/bustools /usr/local/bin

# Set the PATH environment variable
ENV PATH="$PATH:/usr/local/bin/kallisto:/usr/local/bin/minimap2"

# # # FOR DEBUG on local machine
# # # Create a directory for Jupyter notebooks
# RUN mkdir /notebooks

# # Copy spec.yaml, copy the notebook
# COPY spec.yaml /notebooks
# COPY preprocess.ipynb /notebooks

# # Install Jupyter Notebook
# RUN pip install jupyter

# # Set the working directory to /notebooks
# WORKDIR /notebooks

# # Expose port 8888 for Jupyter Notebook
# EXPOSE 8888

# # Start Jupyter Notebook on container startup
# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]


# docker build -t eilalan/atomic_update:latest -f Dockerfile_atomic_pipeline_update .
# docker run -it eilalan/atomic_update:latest bash
# docker push eilalan/atomic_update:latest