# Use an official Miniconda3 as a parent image
FROM continuumio/miniconda3

RUN conda create -n utils_env -y python=3.8 && \
    conda install -y -n utils_env -c conda-forge py-bgzip && \
    conda install -y -n utils_env -c bioconda tabix && \
    echo "source activate utils_env" > ~/.bashrc

# Set default command to start /bin/bash
ENV PATH /usr/local/bin:/opt/conda/envs/utils_env/bin:$PATH
ENV CONDA_DEFAULT_ENV utils_env

# 1. docker build -t eilalan/utils_env -f Dockerfile_utils .
# 2. docker run -it eilalan/utils_env:latest
# 3. docker push eilalan/utils_env
