name: IGVF atomic workflows CI

on:
  push:
    branches: [ "dev", "main" ]
    paths:
      -  'modules/igvf-kallisto-bustools/**'
  pull_request:
    branches: [ "dev", "main" ]
    paths:
      -  'modules/igvf-kallisto-bustools/**'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag (default: branch_name)'

env:
  PROJECT_NAME: IGVF atomic workflows CI
  # Github repo name
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  # Region-specific Google Docker repository where GOOGLE_PROJECT/REPOSITORY_NAME can be found
  DOCKER_REGISTRY: docker.io
  DOCKER_PATH: igvf/kallisto-bustools
  TAG: ${{ github.event.inputs.image_tag || github.head_ref || github.ref_name }}

jobs:

  build-for-dockerhub:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/igvf-kallisto-bustools

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker_builder.dockerfile --tag ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_PATH }}:${{ env.TAG }}
    - name: Push image
      run: "docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_PATH }}:${{ env.TAG }}"